version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4576:4576"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - ACCESS_KEY=FAKE
      - SECRET_KEY=FAKE
      - EDGE_PORT=4576
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: workshop
    ports:
      - "27017:27017"